### ISSUE TITLE
Small docs fixes

### ISSUE THREAD

**Issue by pasqenr** [commercionetwork/commercio-sdk.dart#15]
Reviewing the documentation I've found just some small adjustment that should be done:

- [docs/lib/id/id_helper.md](https://github.com/commercionetwork/commercio-sdk.dart/blob/update-guide/docs/lib/id/id_helper.md)
  - The line 64 has a typo error (`diDocument` instead of `didDocument`), should be:
    ```dart
    await IdHelper.setDidDocument(didDocument, wallet);
    ```
- Strings in Dart are usually declared with single quotes but double quotes are not an error
- Tips are not in GitHub markdown syntax. For example:
  ```markdown
  :::tip Some tip :::
   ```
   is not processed by GitHub. Maybe should we use a quote block instead?
- [docs/lib/membership/membership_helper.md](https://github.com/commercionetwork/commercio-sdk.dart/blob/update-guide/docs/lib/membership/membership_helper.md) lines 10-13 the correct method signature is:
   ```dart
   static Future<TransactionResult> inviteUser(
     String userDid, 
     Wallet wallet,
     {StdFee fee}
   ) async
   ```
   with the optional `fee` parameter.
- [docs/lib/mint/mint_helper.md](https://github.com/commercionetwork/commercio-sdk.dart/blob/update-guide/docs/lib/mint/mint_helper.md) at lines 10-14 the openCdp signature should be:
    ```dart
    static Future<TransactionResult> openCdp(
      int amount, 
      Wallet wallet,
      {StdFee fee}
    )
    ```
    with `amount` instead of `commercioTokenAmount`.
- [docs/lib/tx/tx_helper.md](https://github.com/commercionetwork/commercio-sdk.dart/blob/update-guide/docs/lib/tx/tx_helper.md) lines 13-18, the `fee` parameter is now assigned inside the method body and thus the signature become:
    ```dart
    static Future<TransactionResult> createSignAndSendTx(
    List<StdMsg> msgs,
    Wallet wallet, {
    StdFee fee,
    }) async
    ```` 
- [docs/lib/crypto/sign_helper.md](https://github.com/commercionetwork/commercio-sdk.dart/blob/update-guide/docs/lib/crypto/sign_helper.md) the method `signSorted()` should have the signature:
    ```dart
    static Uint8List signSorted(dynamic data, Wallet wallet)
     ```
- [docs/lib/crypto/encryption_helper.md](https://github.com/commercionetwork/commercio-sdk.dart/blob/update-guide/docs/lib/crypto/encryption_helper.md) line 54 should be:
     ```dart
    static Future<RSAPublicKey> getGovernmentRsaPubKey(String lcdUrl) async
    ```
    with `RSAPublicKey` instead of `RSAPubKey`.
- [docs/lib/crypto/keys_helper.md](https://github.com/commercionetwork/commercio-sdk.dart/blob/update-guide/docs/lib/crypto/keys_helper.md)
  - line 12 should be:
    ```dart
     static Future<KeyPair<RSAPublicKey, RSAPrivateKey>> generateRsaKeyPair({
       int bytes = 2048,
       String type,
     }) async
      ```
     with the optional `type` parameter.
  - line 18 should be:
    ```dart
     static Future<Key> generateAesKey({int length = 256}) async
      ```
     with length `256` instead of `356`.

**Comment by zenit70** [comment]
@pasqenr I've updated the documentation according to your instructions, thank you.

>Tips are not in GitHub markdown syntax

Yes, it is a typical syntax of Vuepress; if I remember correctly, it was also used in other documentation of the "Commercio" project. 

Let's hear what @marcotradenet  thinks about it, if it is better to use only standard Markdown syntax or not.
